import { z } from 'zod';

export const CalculationResultSchema = z.object({
  id: z.string().uuid().optional(),
  processId: z.string(),
  processoNumero: z.string().optional(),
  clienteId: z.string(),
  clienteNome: z.string().optional(),
  custosUSD: z.object({
    fobTotal: z.number(),
    freteTotal: z.number(),
    seguroTotal: z.number(),
    cifTotal: z.number(),
  }),
  cambio: z.object({
    cdiAM: z.number(),
    txSpotCompra: z.number(),
    txFuturaVenc: z.number(),
    taxaDolarFiscal: z.number(),
    valorCIFbrl: z.number(),
  }),
  impostos: z.any(),
  creditos: z.any(),
  despesas: z.any(),
  encargos: z.any(),
  custos: z.any(),
  precos: z.any(),
  movimentos: z.array(z.object({
    data: z.string(),
    historico: z.string(),
    diasCorridos: z.number(),
    txSpot: z.number(),
    valorUSD: z.number(),
    encargos: z.number(),
    total: z.number(),
    taxaAnualUsada: z.number().optional(),
    taxaDiariaUsada: z.number().optional(),
    baseDias: z.number().optional(),
    formula: z.string().optional(),
  })),
  summary: z.object({
    numeroMovimentos: z.number(),
    totalDesembolso: z.number(),
    calculadoEm: z.string(),
    calculationDate: z.string().optional(),
    taxaCDI: z.number().optional(),
    taxaConexos: z.number().optional(),
    effectiveRate: z.number().optional(),
  }),
  totalDisburse: z.number(),
  totalInterest: z.number(),
  totalLostInterest: z.number().optional(),
  totalCharges: z.number(),
  hasExistingInterest: z.boolean().optional(),
  payments: z.array(z.any()),
  inputSnapshot: z.object({
    originalInput: z.any(),
    cdiSource: z.enum(['bcb', 'conexos', 'manual']),
    cdiConexosRaw: z.number().optional(),
    cdiUsado: z.number(),
    baseDias: z.union([z.literal(360), z.literal(252)]),
    fetchedAt: z.string(),
    configUsado: z.object({
      filCod: z.number(),
      impCod: z.number(),
      ctpCod: z.number(),
      usnCod: z.string(),
      calcBase: z.union([z.literal(360), z.literal(252)]),
    }),
    movimentosSource: z.enum(['frontend', 'conexos']),
  }).optional(),
});

// ── v2: Payload por item ─────────────────────────────────────────

export const CalculationItemSchema = z.object({
  id: z.string(),
  type: z.enum(['contract', 'expense', 'tax', 'tax_comercializacao', 'tax_di']),
  label: z.string(),
  valorBase: z.number().nonnegative(),
  moeda: z.string(),
  valorMoedaOriginal: z.number().optional(),
  prazoEmDias: z.number().int().nonnegative(),
  dataBase: z.string(),
  dataVencimento: z.string(),
  cdiAoAno: z.number().nonnegative(),
  spread: z.number().min(0),
  taxaEfetiva: z.number().nonnegative(),
  iofValue: z.number().nonnegative().optional(),
  baseDias: z.union([z.literal(360), z.literal(252)]),
  encargosCalculados: z.number().nonnegative(),
  formula: z.string(),
  taxaFechamento: z.number().nullable().optional(),
  taxaPtaxDI: z.number().nullable().optional(),
  taxaSpotDoDia: z.number().nullable().optional(),
  taxaSpotNegociada: z.number().nullable().optional(),
  taxaFutura: z.number().nullable().optional(),
  contasProjeto: z.array(z.string()).optional(),
  detalhesDespesa: z.array(z.object({
    contaProjeto: z.string(),
    encargo: z.string(),
    dataConversao: z.string(),
    valorBRL: z.number(),
    // Pode ser negativo quando valorBRL é um crédito/estorno (Conexos)
    encargosProporcionais: z.number().optional(),
    valorFull: z.number().optional(),
    valorNacionalizacao: z.number().optional(),
    isDelta: z.boolean().optional(),
  })).optional(),
});

export const CalculationSavePayloadSchema = z.object({
  processId: z.string(),
  processoNumero: z.string(),
  clienteId: z.string(),
  clienteNome: z.string(),
  refExterna: z.string(),
  emissionDate: z.string(),
  items: z.array(CalculationItemSchema).min(1),
  totalEncargos: z.number().nonnegative(),
  totalValorBase: z.number().nonnegative(),
  calculadoEm: z.string(),
  payloadVersion: z.literal(2),
});
